### ISSUE TITLE
I am getting some error

### ISSUE THREAD

**Issue by ghost** [waleedahmad/laravel-stream#1]
C:\xampp\htdocs\video>php artisan queue:work --tries=3 --timeout=8600
[2019-04-15 11:23:55][10] Processing: App\Jobs\ConvertVideoForStreaming
[2019-04-15 11:23:57][11] Processing: App\Jobs\ConvertVideoForStreaming
[2019-04-15 11:23:57][12] Processing: App\Jobs\ConvertVideoForStreaming
[2019-04-15 11:23:57][12] Failed:     App\Jobs\ConvertVideoForStreaming

Please Solve it

**Comment by chisumo2016** [comment]
I am getting the same error as you.

**Comment by waleedahmad** [comment]
Check `failed_jobs` table in your database for any exceptions raised when this queued job failed. Without the exception, it's impossible for me to help you guys.

**Comment by vantrung1001** [comment]
Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command C:\FFmpeg\bin\ffmpeg.EXE -y -i "C:\xampp\htdocs\trung\storage\app/public\rGwoJhKcjzwU98xe.mp4" -vcodec libx264 -acodec libmp3lame -b:v 500k -refs 6 -coder 1 -sc_threshold 40 -flags +loop -me_range 16 -subq 7 -i_qfactor 0.71 -qcomp 0.6 -qdiff 4 -trellis 1 -b:a 128k -vf "[in]scale=960:540 [out]" -pass 1 -passlogfile "C:\Users\vantr\AppData\Local\Temp\ffmpeg-passes5e25206f88dc572k08/pass-5e25206f89075" "C:\xampp\htdocs\trung\storage\app/public\rGwoJhKcjzwU98xe.mp4" in C:\xampp\htdocs\trung\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php:100
Stack trace:
#0 C:\xampp\htdocs\trung\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php(72): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure('C:\\FFmpeg\\bin\\f...')
#1 C:\xampp\htdocs\trung\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(209): Alchemy\BinaryDriver\ProcessRunner->run(Object(Symfony\Component\Process\Process), Object(SplObjectStorage), false)
#2 C:\xampp\htdocs\trung\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\AbstractBinary.php(137): Alchemy\BinaryDriver\AbstractBinary->run(Object(Symfony\Component\Process\Process), false, Array)
#3 C:\xampp\htdocs\trung\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php(96): Alchemy\BinaryDriver\AbstractBinary->command(Array, false, Array)
#4 [internal function]: FFMpeg\Media\AbstractVideo->save(Object(FFMpeg\Format\Video\X264), 'C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\Media.php(133): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\MediaExporter.php(117): Pbmedia\LaravelFFMpeg\Media->__call('save', Array)
#7 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\MediaExporter.php(75): Pbmedia\LaravelFFMpeg\MediaExporter->saveAudioOrVideo('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\trung\app\Jobs\ConvertVideoForStreaming.php(61): Pbmedia\LaravelFFMpeg\MediaExporter->save('rGwoJhKcjzwU98x...')
#9 [internal function]: App\Jobs\ConvertVideoForStreaming->handle()
#10 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#15 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#16 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#17 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertVideoForStreaming), false)
#19 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#20 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#21 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(277): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#22 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#23 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#24 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#25 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#26 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#27 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#29 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#30 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call(Array)
#31 C:\xampp\htdocs\trung\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#33 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 C:\xampp\htdocs\trung\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 {main}

Next FFMpeg\Exception\RuntimeException: Encoding failed in C:\xampp\htdocs\trung\vendor\php-ffmpeg\php-ffmpeg\src\FFMpeg\Media\AbstractVideo.php:106
Stack trace:
#0 [internal function]: FFMpeg\Media\AbstractVideo->save(Object(FFMpeg\Format\Video\X264), 'C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\Media.php(133): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\MediaExporter.php(117): Pbmedia\LaravelFFMpeg\Media->__call('save', Array)
#3 C:\xampp\htdocs\trung\vendor\pbmedia\laravel-ffmpeg\src\MediaExporter.php(75): Pbmedia\LaravelFFMpeg\MediaExporter->saveAudioOrVideo('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\trung\app\Jobs\ConvertVideoForStreaming.php(61): Pbmedia\LaravelFFMpeg\MediaExporter->save('rGwoJhKcjzwU98x...')
#5 [internal function]: App\Jobs\ConvertVideoForStreaming->handle()
#6 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#9 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#10 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#11 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#12 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoForStreaming))
#13 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertVideoForStreaming), false)
#15 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#16 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#17 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(277): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#18 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#19 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(102): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#20 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#21 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#22 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#23 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Container\Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Command.php(183): Illuminate\Container\Container->call(Array)
#27 C:\xampp\htdocs\trung\vendor\symfony\console\Command\Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(886): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 C:\xampp\htdocs\trung\vendor\symfony\console\Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Console\Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 C:\xampp\htdocs\trung\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 C:\xampp\htdocs\trung\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}
